clip_model_name: open_clip:hf-hub:chs20/FARE4-ViT-B-32-laion2B-s34B-b79K
device: auto
gradient_layer_accumulation: average
gradient_layer_smoothness: 0.01
init_random_mean: 0.3
init_random_var: 0.1
initialize: random
num_iterations: 1000
output_gradient_layer: false
source_model:
  name: pixels
  params:
    channels: RGB
    size:
    - 224
    - 224
targets:
- active: true
  batch_size: 1
  clip_grad_above_percent: 0.0
  clip_grad_below_percent: 0.0
  clip_grad_norm: 0.0
  grad_accum_steps: 1
  mask_layer: ''
  optimizer:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    fused: false
    learnrate: 0.01
    optimizer: Adam
    weight_decay: 0.0
  target_features:
  - image: ''
    text: pixelart graphics
    type: text
    weight: 1.0
  - image: ''
    text: letters
    type: text
    weight: -1.0
  transformations:
  - name: random_affine
    params:
      active: true
      degrees_min_max:
      - -5.599999999999998
      - 5.0
      interpolation: bilinear
      scale_min_max:
      - 0.9
      - 1.1
      shear_min_max:
      - 0.0
      - 0.0
      translate_xy:
      - 0.1
      - 0.1
  - name: random_crop
    params:
      active: true
      pad_if_needed: true
      padding_mode: constant
      size: 224
