clip_model_name: ViT-B/32
device: auto
num_iterations: 100
source_model:
  name: pixels
  params:
    channels: RGB
    size:
    - 224
    - 224
targets:
- batch_size: 1
  learnrate: 0.01
  prompt: pixelart graphics
  transformations:
  - name: random_affine
    params:
      active: true
      degrees_min_max:
      - -5.599999999999998
      - 5.0
      interpolation: bilinear
      scale_min_max:
      - 0.9
      - 1.1
      shear_min_max:
      - 0.0
      - 0.0
      translate_xy:
      - 0.1
      - 0.1
  - name: random_crop
    params:
      active: true
      size: 224
